[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/taskflow"
  status = 200
