[build]
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/bfhl/*"
  to = "/.netlify/functions/taskflow/bfhl/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/taskflow/:splat"
  status = 200
